# Generated by Django 4.0.6 on 2022-07-24 23:02

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_card_appellate_alter_card_cassation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='case_number',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(main.models.get_min_length_case_number, message='Для продолжения работы с формой необходимо ввести минимум 3 символа')], verbose_name='Номер дела:'),
        ),
        migrations.AlterField(
            model_name='card',
            name='counter',
            field=models.CharField(blank=True, choices=[('None', ''), ('Удовлетворено', 'Удовлетворено'), ('Удовлетворено в части', 'Удовлетворено в части'), ('Отказано', 'Отказано')], max_length=200, null=True, verbose_name='Встречное решение первой инстанции'),
        ),
        migrations.AlterField(
            model_name='card',
            name='intial',
            field=models.CharField(blank=True, choices=[('None', ''), ('Удовлетворено', 'Удовлетворено'), ('Удовлетворено в части', 'Удовлетворено в части'), ('Отказано', 'Отказано')], max_length=200, null=True, verbose_name='Первоначальное решение первой инстанции'),
        ),
    ]
